{{- if .Values.createSecrets }}
{{- $_ := include "kubex-automation-engine.kubexUsername" . -}}
{{- $_ := include "kubex-automation-engine.kubexEpassword" . -}}
{{- $_ := include "kubex-automation-engine.kubexUrl" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.configSecretName | default "kubex-gateway-config" }}
  namespace: {{ include "kubex-automation-engine.namespace" . }}
  labels:
    {{- include "kubex-automation-engine.labels" . | nindent 4 }}
type: Opaque
data:
  # These fields should be base64-encoded. Helm will do this with the b64enc function.
  username: {{ .Values.kubexCredentials.username | b64enc | quote }}
  epassword: {{ .Values.kubexCredentials.epassword | b64enc | quote }}
  url: {{ .Values.kubex.url.host | b64enc | quote }}
  DENSIFY_BASE_URL: {{ printf "https://%s" .Values.kubex.url.host | b64enc | quote }}
{{- end }}
