{{- if .Values.webhook.enabled -}}
{{- if not .Values.webhook.certManager.enabled -}}
{{- $_ := include "kubex-automation-engine.gen-certs-data" . -}}
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubex-automation-engine.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "kubex-automation-engine.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "kubex-automation-engine.namespace" . }}/{{ include "kubex-automation-engine.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-automationstrategy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vautomationstrategy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - automationstrategies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-clusterautomationstrategy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vclusterautomationstrategy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusterautomationstrategies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-clusterproactivepolicy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vclusterproactivepolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterproactivepolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-clusterstaticpolicy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vclusterstaticpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterstaticpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-clusterwidegpurebalancingpolicy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vclusterwidegpurebalancingpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterwidegpurebalancingpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-globalconfiguration
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vglobalconfiguration-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - globalconfigurations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-gpuconsolidationpolicy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vgpuconsolidationpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpuconsolidationpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-gpurebalancingpolicy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vgpurebalancingpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpurebalancingpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-policyevaluation
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vpolicyevaluation-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policyevaluations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-proactivepolicy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vproactivepolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proactivepolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ .caCert }}
    {{- end }}
    service:
      name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
      namespace: {{ include "kubex-automation-engine.namespace" . }}
      path: /validate-rightsizing-kubex-ai-v1alpha1-staticpolicy
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: vstaticpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.kubex.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - staticpolicies
  sideEffects: None
{{- end }}
