{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubex-automation-engine.fullname" . }}-webhook-service
  namespace: {{ include "kubex-automation-engine.namespace" . }}
  labels:
    {{- include "kubex-automation-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    {{- include "kubex-automation-engine.selectorLabels" . | nindent 4 }}
{{- end }}
