name: ""
title: null
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
header_pages: ['']
minima:
  skin: auto
