apiVersion: v2
description: Kubex Collection Stack for OpenShift Clusters
name: kubex-collection-openshift
version: 1.0.4
type: application
icon: https://kubex.ai/wp-content/uploads/kubex-logo-landscape.svg
dependencies:
  - name: container-optimization-data-forwarder
    version: "4.*.*"
    repository: https://densify-dev.github.io/helm-charts
  - name: kubex-ephemeral-storage-metrics
    version: "1.*.*"
    repository: https://densify-dev.github.io/helm-charts
    condition: kubex-ephemeral-storage-metrics.enabled
keywords:
- kubex
- densify
- collection
- container
- optimization
- OpenShift
maintainers:
- email: support@kubex.ai
  name: support
