apiVersion: v2
name: kubex-crds
description: CRDs for Kubex Automation Engine
icon: https://kubex.ai/wp-content/uploads/kubex-logo-landscape.svg
version: 1.0.1
keywords:
  - crd
  - kubex
  - automation
