apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubex-echo
  labels:
    app: kubex-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubex-echo
  template:
    metadata:
      labels:
        app: kubex-echo
    spec:
      containers:
      - name: echo
        image: mendhak/http-https-echo:37
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubex-echo
  labels:
    app: kubex-echo
spec:
  selector:
    app: kubex-echo
  ports:
  - name: http
    port: 8080
    targetPort: 8080
