# Use this file for a large k8s cluster (10001+ containers):
kubex-automation-engine:
  resources:
    requests:
      cpu: "2000m"
      memory: "4Gi"
    limits:
      cpu: null
      memory: "6Gi"
  gateway:
    resources:
      requests:
        cpu: "25m"
        memory: "90Mi"
      limits:
        cpu: null
        memory: "500Mi"
  compactionScheduler:
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: null
        memory: "1Gi"
  compactionDescheduler:
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: null
        memory: "2Gi"

kubex-connector:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      memory: "2Gi"
  relay:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        memory: "2Gi"
kubex-ai-cdi:
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      memory: "4Gi"
prometheus:
  server:
    resources:
      requests:
        memory: "20Gi"
        cpu: "2000m"
      limits:
          memory: "40Gi"
  prometheus-node-exporter:
    resources:
      requests:
        memory: "40Mi"
        cpu: "30m"
      limits:
        memory: "100Mi"
beyla:
  resources:
    requests:
      memory: "512Mi"
      cpu: "50m"
    limits:
      memory: "1Gi"
k8s-ephemeral-storage-metrics:
  resources:
    requests:
      cpu: "600m"
      memory: "2Gi"
    limits:
      memory: "3Gi"
