# Use this file for a small k8s cluster (0-5000 containers):
prometheus:
  server:
    resources:
      requests:
        memory: "4Gi"
        cpu: "500m"
      limits:
        memory: "8Gi"
  prometheus-node-exporter:
    resources:
      requests:
        memory: "20Mi"
        cpu: "10m"
      limits:
        memory: "40Mi"
