# Use this file for a small k8s cluster (0-5000 containers):
prometheus:
  server:
    resources:
      requests:
        memory: "4Gi"
        cpu: "500m"
      limits:
        memory: "8Gi"
  prometheus-node-exporter:
    resources:
      requests:
        memory: "20Mi"
        cpu: "10m"
      limits:
        memory: "40Mi"
beyla:
  resources:
    requests:
      memory: "192Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"

k8s-ephemeral-storage-metrics:
  interval: 25
  max_node_concurrency: 15
  client_go_qps: 8
  client_go_burst: 15
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
