# Use this file for a medium k8s cluster (5001-10000 containers):
prometheus:
  server:
    resources:
      requests:
        memory: "10Gi"
        cpu: "1000m"
      limits:
        memory: "20Gi"
  prometheus-node-exporter:
    resources:
      requests:
        memory: "30Mi"
        cpu: "20m"
      limits:
        memory: "80Mi"
