# Use this file for a large k8s cluster (10001+ containers):
prometheus:
  server:
    resources:
      requests:
        memory: "20Gi"
        cpu: "2000m"
      limits:
          memory: "40Gi"
  prometheus-node-exporter:
    resources:
      requests:
        memory: "40Mi"
        cpu: "30m"
      limits:
        memory: "100Mi"
