enabled: true

nameOverride: ""
fullnameOverride: ""

image:
  repository: quay.io/curl/curl
  tag: latest
  pullPolicy: IfNotPresent

# Tolerations for node selection
tolerations: []

# Security contexts
podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

# Resources for the exporter container
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# ServiceMonitor configuration for Prometheus Operator
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}

# Node selector
nodeSelector: {}

# Affinity rules
affinity: {}
