apiVersion: v1
kind: ConfigMap
metadata:
  name: kubex-crds-version
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubex-crds.labels" . | nindent 4 }}
data:
  version: {{ .Chart.Version | quote }}
