{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubex-ai-cdi.clusterRoleBindingName" . }}
  labels:
    app: {{ include "kubex-ai-cdi.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- if .Values.extraLabels }}
    {{- toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.extraAnnotations }}
  annotations:
    {{- toYaml .Values.extraAnnotations | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubex-ai-cdi.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubex-ai-cdi.clusterRoleName" . }}
{{- end }}
