{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubex-ai-cdi.serviceAccountName" . }}
  labels:
    app: kubex-ai-cdi
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- if .Values.extraLabels }}
    {{- toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.extraAnnotations }}
  annotations:
    {{- toYaml .Values.extraAnnotations | nindent 4 }}
  {{- end }}
{{- end }}
