{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubex-ai-cdi.serviceName" . }}
  labels:
    {{- include "kubex-ai-cdi.selectorLabels" . | nindent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with omit .Values.extraLabels "app" "app.kubernetes.io/name" "app.kubernetes.io/instance" }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
    name: http
  selector:
    app: {{ include "kubex-ai-cdi.name" . }}
{{- end }}
