apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-service" (include "kubex-ai-cdi.fullname" .)) .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ include "kubex-ai-cdi.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
    name: http
  selector:
    {{- include "kubex-ai-cdi.selectorLabels" . | nindent 4 }}
