apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ include "kubex-ai-cdi.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- if .Values.extraLabels }}
    {{- toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.extraAnnotations }}
  annotations:
    {{- toYaml .Values.extraAnnotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
    name: http
  selector:
    app: {{ include "kubex-ai-cdi.name" . }}
