apiVersion: v2
name: node-labeler
description: A Helm chart for deploying the node-labeler controller
type: application
version: 0.1.0
keywords:
  - kubex
  - node
  - labels
maintainers:
  - name: support
    email: support@kubex.ai
icon: https://www.kubex.ai/wp-content/uploads/kubex-by-densify-logo.png
