nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: densify/node-labeler
  tag: 0.0.3
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  annotations: {}
  labels: {}

rbac:
  create: true

leaderElection:
  enabled: true

metrics:
  enabled: false
  secure: true
  bindAddress: ":8443"

healthProbe:
  bindAddress: ":8081"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 1Gi

nodeSelector: {}
affinity: {}
tolerations:
  - key: "kubernetes.io/arch"
    operator: "Exists"
    effect: "NoSchedule"
topologySpreadConstraints: []

extraArgs: []
