{{- include "common.checkValues" . -}} # As this is the only template in the chart, the checkValues function is called here to verify that all values - including those of the subcharts - have been set properly in values-edit.yaml
{{- if .Values.stack.densify.createSecret }}
apiVersion : v1
kind : Secret
metadata :
  name : densify-api-secret
  namespace: {{ template "common.namespace" . }}
type : Opaque
data : 
  username : {{ required ".Values.stack.densify.username is required" .Values.stack.densify.username | b64enc | quote }}
  epassword : {{ required ".Values.stack.densify.encrypted_password is required" .Values.stack.densify.encrypted_password | b64enc | quote }}
{{- end }}
