{{- include "common.checkValues" . }}
{{ if .Values.stack.densify.createSecret }}
{{- $host := index .Values "container-optimization-data-forwarder" "config" "forwarder" "densify" "url" "host" | trim -}}
apiVersion: v1
kind: Secret
metadata:
  name: densify-api-secret
  namespace: {{ template "common.namespace" . }}
type: Opaque
data:
  username: {{ required ".Values.stack.densify.username is required" .Values.stack.densify.username | b64enc | quote }}
  epassword: {{ required ".Values.stack.densify.encrypted_password is required" .Values.stack.densify.encrypted_password | b64enc | quote }}
  url: {{ $host | b64enc | quote }}
  DENSIFY_BASE_URL: {{ printf "https://%s" $host | b64enc | quote }}
{{- end }}
