{{- if and .Values.openshift.enabled (index .Values "gpu-process-exporter" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-gpu-process-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gpu-process-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gpu-process-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
