{{- $rbac := .Values.rbac | default dict -}}
{{- $cdi := $rbac.permissions.cdi | default dict -}}
{{- $serviceAccount := $cdi.serviceAccount | default dict -}}
{{- $cdiValues := index .Values "kubex-ai-cdi" | default dict -}}
{{- $cdiRbac := $cdiValues.rbac | default dict -}}
{{- $extraLabels := $cdiValues.extraLabels | default dict -}}
{{- $extraAnnotations := $cdiValues.extraAnnotations | default dict -}}
{{- if and $cdiValues.enabled $rbac.create (not ($cdiRbac.enabled | default false)) (dig "create" false $serviceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "kubex-ai-cdi-sa" (dig "name" "" $serviceAccount) }}
  namespace: {{ template "common.namespace" . }}
  labels:
    app: kubex-ai-cdi
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if $extraLabels }}
    {{- toYaml $extraLabels | nindent 4 }}
    {{- end }}
  {{- if $extraAnnotations }}
  annotations:
    {{- toYaml $extraAnnotations | nindent 4 }}
  {{- end }}
{{- end }}
