apiVersion: v2
name: gpu-process-exporter
description: A Helm chart for gpu-process-exporter
type: application
icon: https://kubex.ai/wp-content/uploads/kubex-logo-landscape.svg
version: 1.0.0
keywords:
- kubex
- gpu
- process
- exporter
maintainers:
- email: support@kubex.ai
  name: support
