{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubex-automation-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: kubex-automation-tls
  duration: {{ .Values.certmanager.duration | default "720h" }} # Certificate validity duration
  renewBefore: {{ .Values.certmanager.renewBefore | default "240h" }} # Time before expiration to trigger renewal
  privateKey:
    rotationPolicy: {{ .Values.certmanager.rotationPolicy | default "Always" }}
  commonName: kubex-webhook-service.{{ .Release.Namespace }}.svc
  dnsNames:
    - kubex-webhook-service.{{ .Release.Namespace }}.svc
    - kubex-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: kubex-selfsigned-cluster-issuer
    kind: ClusterIssuer
{{- end }}