{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: densify-automation-cert
  namespace: {{ template "common.namespace" . }}
spec:
  secretName: densify-automation-tls
  duration: {{ .Values.certmanager.duration | default "720h" }} # Certificate validity duration
  renewBefore: {{ .Values.certmanager.renewBefore | default "240h" }} # Time before expiration to trigger renewal
  commonName: webhook-service.{{ template "common.namespace" . }}.svc
  dnsNames:
    - densify-webhook-service.{{ template "common.namespace" . }}.svc
    - densify-webhook-service.{{ template "common.namespace" . }}.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
{{- end }}