apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.metadataName }}
  {{- if .Values.certmanager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ template "common.namespace" . }}/densify-automation-cert
  {{- end }}
webhooks:
  {{- range .Values.webhooks }}
  - name: {{ .name }}
    clientConfig:
      service:
        name: densify-webhook-service
        namespace: {{ $.Release.Namespace }}
        path: {{ .path }}
      {{- if not $.Values.certmanager.enabled }}
      caBundle: {{ $.Values.webhookCert.caBundle | quote }}
      {{- else }}
      # cert-manager will inject this
      {{- end }}
    failurePolicy: Ignore
    reinvocationPolicy: IfNeeded
    rules:
      - operations:
          {{- toYaml .operations | nindent 10 }}
        apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
        scope: Namespaced
    {{- if and .namespaceSelector (or .namespaceSelector.matchLabels .namespaceSelector.matchExpressions) }}
    namespaceSelector:
      {{- if .namespaceSelector.matchLabels }}
      matchLabels:
          {{- toYaml .namespaceSelector.matchLabels | nindent 8 }}
        {{- end }}
      {{- if .namespaceSelector.matchExpressions }}
      matchExpressions:
        {{- toYaml .namespaceSelector.matchExpressions | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if and .objectSelector (or .objectSelector.matchLabels .objectSelector.matchExpressions) }}
    objectSelector:
      {{- if .objectSelector.matchLabels }}
      matchLabels:
        {{- toYaml .objectSelector.matchLabels | nindent 8 }}
      {{- end }}
      {{- if .objectSelector.matchExpressions }}
      matchExpressions:
        {{- toYaml .objectSelector.matchExpressions | nindent 8 }}
      {{- end }}
    {{- end }}
    admissionReviewVersions: ["v1"]
    sideEffects: "None"
    timeoutSeconds: 10
  {{- end }}
