apiVersion: v1
kind: Service
metadata:
  name: densify-webhook-service
  namespace: {{ template "common.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
      app: densify-webhook