apiVersion: v1
kind: Service
metadata:
  name: kubex-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
      app: kubex-webhook