certmanager:
  enabled: false # Enable if you're using cert-manager to manage TLS certificates.

config:
  DENSIFY_BASE_URL: https://<customerName>.densify.com # Base URL of the Densify API endpoint.
  CLUSTER_NAME: <clusterName> # Name of the Kubernetes cluster

secret:
  username: <username> # This is the username to access Densify
  epassword: <epassword> # This is the encrypted password to access Densify

policy:
  automationenabled: true # Global Switch to enable/disable automation for the cluster
  defaultpolicy: cpu-reclaim # Default policy if no specific policy has been defined in the webhook definition
  remoteenablement:
    false # false: Enable automation within webhook definition only
    # true:  Enable automation within webhook definition and Densify UI
webhook:
  caBundle: null # Placeholder for CA bundle, will be filled by cert-manager if enabled.

webhooks:
  - name: densify-resource.optimization.webhook # Name of the Kubernetes MutatingWebhookConfiguration.
    path: /mutate/cpu-reclaim # Path for the mutating webhook including automation policy name.
    operations: # Kubernetes API operations that trigger this webhook.
      - CREATE
      - UPDATE
    #objectSelector: # Only target pods with the specified label.
    #  matchLabels:
    #    kubexAutomation: "true" # Ensures only labeled pods are mutated; prevents affecting all pods.
    namespaceSelector: # Define the list of namespaces to include or exclude
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn # Use 'NotIn' to exclude namespaces and 'In' to include namespaces
          values:
            - kube-system
            - densify

pv:
  provisionPV: false # Only use for testing in kind clusters
  accessMode: ReadWriteOnce
  #storageClassName: default
