apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubex-ephemeral-storage-metrics.fullname" . }}
  labels:
    {{- include "kubex-ephemeral-storage-metrics.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
