apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubex-ephemeral-storage-metrics.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubex-ephemeral-storage-metrics.labels" . | nindent 4 }}
data:
  ephemeral-exporter.sh: |
{{ .Files.Get "ephemeral-exporter.sh" | indent 4 }}
