apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubex-ephemeral-storage-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubex-ephemeral-storage-metrics.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9102
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "kubex-ephemeral-storage-metrics.selectorLabels" . | nindent 4 }}
