apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubex-ephemeral-storage-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubex-ephemeral-storage-metrics.labels" . | nindent 4 }}
